### ISSUE TITLE
[Feat] Criar listagem de repositórios

### ISSUE THREAD

**Issue by gabrielrom** [gabrielrom/github-search#2]
## Descrição 
Como usuário, quero poder listar todos os repositórios, para conseguir acessar suas informações e seus respectivos PRs.

## Critérios de aceitação 
* É necessário  listar todos os repositórios que foram desenvolvidos na linguagem swift
* Cada repositório precisa ter as seguintes infomacoes:

   * Nome do repositório;
   * Descrição do Repositório;
   * Nome / Foto do autor;
   * Número de Stars;
   * Número de Forks
 * A listagem precisa ser scrollavel e também conter infinity scroll

## Tasks
- [ ] Criar a tela de home seguindo o design do [figma](https://www.figma.com/file/X9PcANEaKLkjZMrlMSyiqz/Desafio---Git?node-id=2%3A208)
- [ ] Utilizar arquitetura MVVM-C
- [ ] Puxar os repositorios da api do github
- [ ] Adicionar um target de navegação para a listagem dos PRs ao clicar em um repositório especifico
